name: EdgeGuardian Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use EdgeGuardian Client Action
        uses: edgeguardian/actions-client@v1
        with:
          api_key: ${{ secrets.EDGE_GUARDIAN_API_KEY }}
          submit_diagnostics_on_failure: 'true'
          release_channel: 'latest'

      # Add more steps as needed for your workflow after using the EdgeGuardian action
